_pedPool = [
"CFP_C_AFRCHRISTIAN_Civ_1_01",
"CFP_C_AFRCHRISTIAN_Civ_2_01",
"CFP_C_AFRCHRISTIAN_Civ_3_01",
"CFP_C_AFRCHRISTIAN_Civ_4_01",
"CFP_C_AFRCHRISTIAN_Civ_5_01",
"CFP_C_AFRCHRISTIAN_Civ_6_01",
"CFP_C_AFRCHRISTIAN_Civ_7_01",
"CFP_C_AFRCHRISTIAN_Civ_8_01",
"CFP_C_AFRCHRISTIAN_Civ_9_01",
"CFP_C_AFRCHRISTIAN_Civ_10_01",
"CFP_C_AFRCHRISTIAN_Civ_11_01",
"CFP_C_AFRCHRISTIAN_Civ_12_01",
"CFP_C_AFRCHRISTIAN_Civ_13_01",
"CFP_C_AFRCHRISTIAN_Civ_14_01"
];
_motPool = [
"CFP_C_AFRCHRISTIAN_Golf_01",
"CFP_C_AFRCHRISTIAN_Ikarus_01",
"CFP_C_AFRCHRISTIAN_Land_Rover_01",
"CFP_C_AFRCHRISTIAN_Pickup_Old_01",
"CFP_C_AFRCHRISTIAN_Skoda_01",
"CFP_C_AFRCHRISTIAN_SUV_01",
"CFP_C_AFRCHRISTIAN_SUV_2_01",
"CFP_C_AFRCHRISTIAN_Truck_Boxer_01",
"CFP_C_AFRCHRISTIAN_UAZ_Open_01",
"CFP_C_AFRCHRISTIAN_Zamak_01"
];

[_pedPool, _motPool]

