_pedPool = [
"CFP_C_AFRISLAMIC_Civ_1_01",
"CFP_C_AFRISLAMIC_Civ_2_01",
"CFP_C_AFRISLAMIC_Civ_3_01",
"CFP_C_AFRISLAMIC_Civ_4_01",
"CFP_C_AFRISLAMIC_Civ_5_01",
"CFP_C_AFRISLAMIC_Civ_6_01",
"CFP_C_AFRISLAMIC_Civ_7_01",
"CFP_C_AFRISLAMIC_Civ_8_01",
"CFP_C_AFRISLAMIC_Civ_9_01",
"CFP_C_AFRISLAMIC_Civ_10_01",
"CFP_C_AFRISLAMIC_Civ_11_01",
"CFP_C_AFRISLAMIC_Civ_12_01"
];

_motPool = [
"CFP_C_AFRISLAMIC_Datsun_Pickup_Old_01",
"CFP_C_AFRISLAMIC_Land_Rover_01",
"CFP_C_AFRISLAMIC_Skoda_Blue_01",
"CFP_C_AFRISLAMIC_Skoda_White_01",
"CFP_C_AFRISLAMIC_Truck_Boxer_01",
"CFP_C_AFRISLAMIC_Ural_Blue_01",
"CFP_C_AFRISLAMIC_Ural_Yellow_01",
"CFP_C_AFRISLAMIC_Zamak_01"
];

[_pedPool, _motPool]