class LRG_AI {

	tag = "LR";
	class AI {

		file = "z\LRG Fundamentals\addons\AI\Functions";
		class InfantryGarrison {};
		class moduleAISpawns {};
		class SetInitialAI {};
		class SetUnitSkill {};
		class SpawnAI {};
		class SpawnAIZeusWrapper {};
	};

	class Factions {

		file = "z\LRG Fundamentals\addons\AI\Functions\Factions";
		class BLU_F {};
		class BLU_T_F {};
		class CFP_O_ABUSAYYAF {};
		class CFP_O_ALQAEDA {};
		class CFP_O_ALSHABAAB {};
		class CFP_O_ANSARALLAH {};
		class CFP_O_BOKOHARAM {};
		class CFP_O_CFRebels {};
		class CFP_O_CHDKZ_SNW {};
		class CFP_O_HAMAS {};
		class CFP_O_HEZBOLLAH {};
		class CFP_O_IQARMY {};
		class CFP_O_IRARMY {};
		class CFP_O_IS {};
		class CFP_O_NKARMY {};
		class CFP_O_RUARMY_DES {};
		class CFP_O_RUMVD {};
		class CFP_O_SDARMY {};
		class CFP_O_SDMilitia {};
		class CFP_O_SOREBEL {};
		class CFP_O_SSREBELS {};
		class CFP_O_SYARMY {};
		class CFP_O_TBAN {};		
		class CUP_B_CZ {};
		class CUP_B_GB {};
		class CUP_B_GER {};
		class CUP_B_US_Army {};
		class CUP_I_NAPA {};
		class CUP_I_PMC_ION {};
		class CUP_I_RACS {};
		class CUP_I_TK_GUE {};
		class CUP_I_UN {};
		class CUP_O_ChDKZ {};
		class CUP_O_RU {};
		class CUP_O_SLA {};
		class CUP_O_TK {};
		class CUP_O_TK_MILITIA {};
		class IND_C_F {};
		class IND_F {};
		class LOP_AA {};
		class LOP_AFR_OPF {};
		class LOP_AM_OPF {};
		class LOP_BH {};
		class LOP_ChDKZ {};
		class LOP_IA {};
		class LOP_IRA {};
		class LOP_IRAN {};
		class LOP_ISTS_OPF {};
		class LOP_NAPA {};
		class LOP_PESH_IND {};
		class LOP_PMC {};
		class LOP_RACS {};
		class LOP_SLA {};
		class LOP_TKA {};
		class LOP_UA {};
		class LOP_UKR {};
		class LOP_UN {};
		class LOP_US {};
		class LOP_UVF {};
		class OPF_F {};
		class OPF_T_F {};
		class OPTRE_Ins {};
		class OPTRE_UNSC {};
		class rhs_faction_msv {};
		class rhs_faction_usarmy_d {};
		class rhs_faction_usarmy_wd {};
		class rhs_faction_vdv {};
		class rhs_faction_vmf {};
		class rhsgref_faction_cdf_ground {};
		class rhsgref_faction_chdkz {};
		class rhsgref_faction_chdkz_g {};
		class rhsgref_faction_nationalist {};
		class rhssaf_faction_army {};
		class rhssaf_faction_un {};
		class TEC_CSAT {};
		class TEC_CSAT_Pacific {};
		class UK3CB_CCM_O {};
		class UK3CB_TKA_O {};
		class UK3CB_TKM_O {};
		class UK3CB_TKP_O {};
		class UK3CB_CCM_I {};
		class UK3CB_TKA_I {};
		class UK3CB_TKM_I {};
		class UK3CB_TKP_I {};
		class UK3CB_UN_I {};
		class UK3CB_ANA_B {};
		class UK3CB_ANP_B {};
		class UK3CB_CCM_B {};
		class UK3CB_TKA_B {};
		class UK3CB_TKM_B {};
		class UK3CB_TKP_B {};
		class UK3CB_UN_B {};
		class UK3CB_BAF_Faction_Army_Arctic {};
		class UK3CB_BAF_Faction_Army_Desert {};
		class UK3CB_BAF_Faction_Army_MTP {};
		class UK3CB_BAF_Faction_Army_Temperate {};
		class UK3CB_BAF_Faction_Army_Tropical {};
		class UK3CB_BAF_Faction_Army_Woodland {};
		class UNSUNG_E_NVA {};
	};
};

class DERP {
    tag = "DERP";

    class General {
        file = "z\LRG Fundamentals\addons\AI\Functions";
        class AIOccupyBuilding {};
        class randomPos {};
        class ZenOccupy {};
    };
};
