#!/bin/sh

cd tools

echo -e "\n=== Compiling documentation ===\n"
if [ ! -d ../docs ]
then
  mkdir ../docs
fi
cp overview.txt LRG_Logo.png ../addons

naturaldocs -r -i "../addons" -xi "../addons/main/Functions/AIS" -o HTML "../docs" -p "lrg-fundamentals" -s Default lrg
rm ../addons/{overview.txt,LRG_Logo.png}